#!/usr/bin/env python3

import argparse
from google.cloud import bigquery

description = 'kcidb-submit - Submit test results to kernelci.org database'
parser = argparse.ArgumentParser(description=description)
parser.add_argument(
    '-d', '--dataset',
    help='Dataset name',
    required=True
)
parser.add_argument(
    '-n', '--name',
    help='Test name',
    required=True
)
parser.add_argument(
    '-r', '--result',
    help='Test result (PASS/FAIL)',
    required=True,
    choices=['PASS', 'FAIL']
)
args = parser.parse_args()

client = bigquery.Client()
