#!/usr/bin/env python3

import argparse
from google.cloud import bigquery

description = 'kcidb-init - Initialize a kernelci.org database'
parser = argparse.ArgumentParser(description=description)
parser.add_argument(
    '-d', '--dataset',
    help='Dataset name',
    required=True
)
args = parser.parse_args()

table_schema_map = dict(
    tests=[
        bigquery.schema.SchemaField(
            "name", "STRING",
            description="Test name"
        ),
        bigquery.schema.SchemaField(
            "result", "STRING",
            description="Test result"
        ),
    ]
)

client = bigquery.Client()
dataset_ref = client.dataset(args.dataset)

for table_name, table_schema in table_schema_map.items():
    table_ref = dataset_ref.table("tests")
    table = bigquery.table.Table(table_ref, schema=table_schema)
    client.create_table(table)
