#!/usr/bin/env python3
"""Handle Issue Editor WebUI requests"""

import os
from kcidb.issue_editor import app

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", 8080)))
